sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hardikshakya/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true hardikshakya/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-923445559289"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
